# Generated by Django 5.1.2 on 2024-11-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0005_remove_hoso_ma_benh_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='benhan',
            name='dieu_tri',
            field=models.CharField(default='Không xác định', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benhan',
            name='trieu_chung',
            field=models.CharField(default='Không có triệu chứng', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoso',
            name='gioi_tinh',
            field=models.CharField(default='nam', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoso',
            name='sdt',
            field=models.CharField(default='0123456789', max_length=20),
            preserve_default=False,
        ),
    ]
