# Generated by Django 5.1.2 on 2024-11-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0008_adminaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAccount',
        ),
    ]
