# Generated by Django 5.1.2 on 2024-11-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0009_delete_adminaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Nam'), ('Female', 'Nữ')], max_length=10)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id_ba', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='hoso.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='BenhAn',
        ),
        migrations.DeleteModel(
            name='Hoso',
        ),
    ]
