# Generated by Django 5.1.2 on 2024-11-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0010_patient_medicalrecord_delete_benhan_delete_hoso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateField(),
        ),
    ]
