# Generated by Django 5.1.2 on 2024-11-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0011_alter_medicalrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
