# Generated by Django 5.1.2 on 2024-10-31 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hoso', '0002_delete_benhan_delete_hoso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hoso',
            fields=[
                ('so_cccd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dia_chi', models.CharField(blank=True, max_length=50, null=True)),
                ('ma_benh_an', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Benh_an',
            fields=[
                ('ma_benh_an', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngay_kham', models.DateField()),
                ('khoa_dieu_tri', models.CharField(max_length=30)),
                ('chuan_doan', models.CharField(max_length=200)),
                ('so_cccd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoso.hoso')),
            ],
        ),
    ]
