# Generated by Django 5.1.2 on 2024-10-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benh_an',
            new_name='BenhAn',
        ),
    ]
