# Generated by Django 5.1.2 on 2024-11-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoso', '0004_rename_benh_an_benhan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoso',
            name='ma_benh_an',
        ),
    ]
