# Generated by Django 5.1.2 on 2024-11-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bacsi_benhnhan_hosobenhan_delete_medicalrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benhnhan',
            name='soCCCD',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
