# Generated by Django 5.1.2 on 2024-11-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hosobenhan_thoigiankham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosobenhan',
            name='thoiGianKham',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
